Repository chshersh/tool-sync, pull requests merged in 2022-09, with the labels that each got.

#60 Resolves #49
  src/model/release.rs
  src/sync/download.rs
  src/sync/install.rs
  src/sync/progress.rs
Labels: enhancement

#61 [#32] Add tag option to download a specific tool version
  README.md
  src/config/schema.rs
  src/config/toml.rs
  src/model/tool.rs
  src/sync/configure.rs
  src/sync/db.rs
  src/sync/download.rs
  src/sync/install.rs
Labels: enhancement, toml

#64 [#63] Added tag support in download progress
  src/sync.rs
  src/sync/download.rs
  src/sync/install.rs
  src/sync/progress.rs
Labels: enhancement, output

#74 added pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, ⚗️ dx

#79 [#73] adding .precommit yaml
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  Cargo.toml
  README.md
  example-tool-sync-config.toml
  src/sync.rs
  src/sync/configure.rs
  tests/full-database.toml
  tests/only-ripgrep.toml
Labels: documentation, CI, ⚗️ dx

#81 Better CI caching
  .github/workflows/ci.yml
Labels: CI

#80 [#33] Better end-of-sync output
  src/config/schema.rs
  src/infra.rs
  src/infra/client.rs
  src/lib.rs
  src/model/release.rs
  src/model/tool.rs
  src/sync.rs
  src/sync/download.rs
  src/sync/install.rs
  src/sync/prefetch.rs
  src/sync/progress.rs
Labels: enhancement, output

#89 [#57] Adds install command to install known tools
  .github/workflows/ci.yml
  README.md
  src/config/cli.rs
  src/config/schema.rs
  src/lib.rs
  tests/install-ripgrep.toml
Labels: enhancement, CLI

#94 Refactor commands into separate modules
  .github/workflows/ci.yml
  src/config/template.rs
  src/config/toml.rs
  src/infra.rs
  src/infra/err.rs
  src/install.rs
  src/lib.rs
  src/sync.rs
  src/sync/db.rs
  tests/default-config.toml
  tests/only-ripgrep.toml
  tests/sync-full.toml
  tests/sync-ripgrep.toml
Labels: refactoring

#97 [#83] Create 'AssetError' and refactor 'select_asset' function to return it
  README.md
  src/model/release.rs
  src/model/tool.rs
  src/sync/prefetch.rs
Labels: test, refactoring

#100 [#98] changed all formatting functions so they accept a type that implements Display
  src/config/schema.rs
  src/config/toml.rs
  src/infra/err.rs
  src/install.rs
  src/sync/install.rs
  src/sync/prefetch.rs
  src/sync/progress.rs
Labels: output, refactoring

#102 [#54] Adding extra path and added a new error for the case where multiple assets are found
  .github/workflows/ci.yml
  src/model/release.rs
  src/model/tool.rs
  src/sync/archive.rs
  src/sync/db.rs
  src/sync/prefetch.rs
  src/sync/progress.rs
  tests/default-config.toml
  tests/sync-full.toml
Labels: enhancement, config, output

#101 [#56] Improve documentation for v0.2.0
  CHANGELOG.md
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  FUNDING.yml
  README.md
  images/demo.gif
  tests/default-config.toml
Labels: documentation

#104 [#55] Don't require 'exe_name' in the configuration
  CHANGELOG.md
  src/sync/configure.rs
Labels: enhancement, config

#105 Specify 'tool-sync' asset name more precisely
  src/sync/db.rs
Labels: test

#118 [skip ci] added an extra checkbox for CHANGELOG changes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚗️ dx

#114 [#84] refactor of hardcoded tools
  CHANGELOG.md
  src/sync/db.rs
Labels: refactoring

#113 [#92] Install a tool from the config file using `tool sync <tool-name>`
  CHANGELOG.md
  README.md
  src/config/cli.rs
  src/install.rs
  src/lib.rs
  src/sync.rs
Labels: config, CLI

#120 [#119] De-pluralize success message when only 1 tool is installed
  CHANGELOG.md
  src/sync.rs
Labels: output
