Repository chshersh/tool-sync, pull requests merged in 2022-10, with the labels that each got.

#123 Outputs tools URLs in the default-config command
  CHANGELOG.md
  src/config/template.rs
  src/install.rs
  src/sync.rs
  src/sync/db.rs
  tests/default-config.toml
Labels: config, hacktoberfest-accepted

#121 [#82] Adds proxy as a flag and config option
  CHANGELOG.md
  src/config/cli.rs
  src/config/schema.rs
  src/config/toml.rs
  src/infra/client.rs
  src/install.rs
  src/lib.rs
  src/model/tool.rs
  src/sync.rs
  src/sync/configure.rs
  src/sync/install.rs
  src/sync/prefetch.rs
Labels: enhancement, help wanted, hacktoberfest-accepted

#126 [#108] Check prefetched `tool_assets` is not empty before passing it to `SyncProgress::new`
  CHANGELOG.md
  src/sync.rs
Labels: output, hacktoberfest-accepted

#125 [#109] Add `--path` option to the `default-config` command to print default config location instead
  CHANGELOG.md
  README.md
  src/config/cli.rs
  src/lib.rs
Labels: config, CLI, hacktoberfest-accepted

#122 Provide more detailed TOML decoding errors
  src/config/toml.rs
Labels: config, hacktoberfest-accepted

#135 [#128] Uses RepoError::NotFound when fetch_release_info returns 404
  CHANGELOG.md
  src/model.rs
  src/model/repo.rs
  src/sync/prefetch.rs
Labels: output, hacktoberfest-accepted

#137 [#136] Upgrade clap to 4.0
  Cargo.lock
  Cargo.toml
  src/config/cli.rs
  src/config/toml.rs
Labels: dependencies, hacktoberfest-accepted

#140 Upgrade dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies

#134 [#133] Added shell completion
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/completion.rs
  src/config/cli.rs
  src/lib.rs
  tests/bash-completion
  tests/zsh-completion
Labels: documentation, CLI, output, hacktoberfest-accepted

#147 sync/db: add just, hyperfine, k9s, and procs
  .github/workflows/ci.yml
  CHANGELOG.md
  src/sync/db.rs
  tests/default-config.toml
  tests/sync-full.toml
Labels: enhancement, config, hacktoberfest-accepted, tools-support

#142 [#141] Add docstring to the '--proxy' CLI flag
  src/config/cli.rs
Labels: documentation, hacktoberfest-accepted

#144 [#107] Remove dynamically-linked 'tool-sync' asset
  .github/workflows/release.yml
  src/sync/db.rs
Labels: test, CI, hacktoberfest-accepted

#151 renamed 'module' files to their respective mod.rs versions
  src/config/mod.rs
  src/infra/mod.rs
  src/model/mod.rs
  src/sync/mod.rs
Labels: hacktoberfest-accepted, refactoring

#152 feat: remove double debug println calls
  src/infra/client.rs
Labels: output, hacktoberfest-accepted, refactoring
